language: python

dist: xenial

sudo: false

matrix:
    fast_finish: true
    include:
      - { python: "2.7", env: DJANGO=1.9 }
      - { python: "2.7", env: DJANGO=1.10 }
      - { python: "2.7", env: DJANGO=1.11 }

      - { python: "3.5", env: DJANGO=1.9 }
      - { python: "3.5", env: DJANGO=1.10 }
      - { python: "3.5", env: DJANGO=1.11 }
      - { python: "3.5", env: DJANGO=2.0 }
      - { python: "3.5", env: DJANGO=2.1 }

      - { python: "3.6", env: DJANGO=1.10 }
      - { python: "3.6", env: DJANGO=1.11 }
      - { python: "3.6", env: DJANGO=2.0 }
      - { python: "3.6", env: DJANGO=2.1 }

      - { python: "3.7", env: DJANGO=1.10 }
      - { python: "3.7", env: DJANGO=1.11 }
      - { python: "3.7", env: DJANGO=2.0 }
      - { python: "3.7", env: DJANGO=2.1 }

install:
    - pip install tox tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
    email: false
