language: python

dist: xenial

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"

sudo: false

env:
    - DJANGO=1.9
    - DJANGO=1.10
    - DJANGO=1.11
    - DJANGO=2.0
    - DJANGO=2.1
    - DJANGO=2.2

matrix:
    fast_finish: true
    include:
      - { python: "2.7", env: DJANGO=1.9 }
      - { python: "2.7", env: DJANGO=1.10 }
      - { python: "2.7", env: DJANGO=1.11 }

      - { python: "3.5", env: DJANGO=1.9 }
      - { python: "3.5", env: DJANGO=1.10 }
      - { python: "3.5", env: DJANGO=1.11 }
      - { python: "3.5", env: DJANGO=2.0 }
      - { python: "3.5", env: DJANGO=2.1 }
      - { python: "3.5", env: DJANGO=2.2 }

      - { python: "3.6", env: DJANGO=1.10 }
      - { python: "3.6", env: DJANGO=1.11 }
      - { python: "3.6", env: DJANGO=2.0 }
      - { python: "3.6", env: DJANGO=2.1 }
      - { python: "3.6", env: DJANGO=2.2 }

      - { python: "3.7", env: DJANGO=1.10 }
      - { python: "3.7", env: DJANGO=1.11 }
      - { python: "3.7", env: DJANGO=2.0 }
      - { python: "3.7", env: DJANGO=2.1 }
      - { python: "3.7", env: DJANGO=2.2 }

install:
    - pip install tox tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
    email: false
