language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"

sudo: false

env:
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10

matrix:
    fast_finish: true
    include:
      - python: "3.3"
        env: DJANGO=1.8

install:
    - pip install tox tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
    email: false
