language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"

sudo: false

env:
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10
    - DJANGO=1.11

matrix:
    fast_finish: true
    exclude:
      - python: "3.6"
        env: DJANGO=1.8

install:
    - pip install tox tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
    email: false
